spring:
  jpa:
    properties:
      hibernate:
        format_sql: false

  flyway:
    out-of-order: false

server:
  error:
    include-message: never
    include-stacktrace: never

logging:
  level:
    com.tenga: INFO
    root: WARN
